language: python
dist: xenial
sudo: required
python:
  - "3.5"
before_install:
  - sudo apt-get update
install:
  - src/installDependencies.sh
# command to run tests
script:
  - tests/test.sh
  - src/runAll.sh
after_script:
  - cat src/config.json
  - cat export.csv
